{% set version = "2.0.6" %}
}
package:
  name: doltpy
  version: {{ version }}

build:
  script:
    - PIP_NO_INDEX="False" $PYTHON -m pip install --no-deps doltpy=={{ version }}
  entry_points:
    - dolthub-load = doltpy.etl:load_to_dolthub
    - dolt-load = doltpy.etl:load_to_dolt

requirements:
  build:
    - python {{ python }}
    - pip
  run:
    - python
    - attrs >=19.3.0
    - decorator >=4.4.2
    - numpy >=1.19.0
    - packaging >=20.4
    - pandas>=1.0.5
    - pluggy >=0.13.1
    - protobuf >=3.12.2
    - psutil >=5.7.2
    - py >=1.9.0
    - pyparsing >=2.4.7
    - python-dateutil >=2.8.1
    - pytz >=2020.1
    - retry >=0.9.2
    - six >=1.15.0
    - SQLAlchemy >=1.3.18
    - wcwidth >=0.2.5
    - more-itertools>=8.6.0
    - mysql-connector-python >=8.0.20
  pip:
    - doltcli >=0.1.4

about:
  home: https://github.com/dolthub/doltpy
