name: Doltpy Tests

on: push

jobs:
  # Run test suite across all major OS types
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #python-version: ['3.7', '3.8', '3.9']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Execute pytest
        run: poetry run pytest -m 'not sql_sync' doltpy --cov-report=xml,term
      - name: Send to codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
      - name: Execute black
        run: poetry run black doltpy -t py37
      - name: Execute mypy
        run: poetry run mypy doltpy
      - name: Check lockfile
        run: poetry lock & git diff --exit-code poetry.lock
      #- name: Discord Notify
        #if: always()
        #uses: dolthub/ga-discord-notify@master
        #with:
          #job-status: ${{ job.status }}
          #webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          #notify-on-success: false
