name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.23.4'
        required: true

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Doltpy version
        run: sed -i 's/version =.*/version = "'"$VERSION"'"/' "$FILE"
        env:
          FILE: setup.py
          VERSION: ${{ github.event.inputs.version }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: ${{ format('[ga-bump-release] update Doltpy version to {0}', github.event.inputs.version) }}
          add: ${{ format('{0}/setup.py', github.workspace) }}
          cwd: "."
      - name: Discord Notify
        if: always()
        uses: dolthub/ga-discord-notify@master
        with:
          job-status: ${{ job.status }}
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          notify-on-success: false

  create-release:
    needs: bump-version
    name: Create Release
    runs-on: ubuntu-18.04
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

  publish:
    needs: bump-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout release
      run: |
        git fetch --tags --all
        git checkout tags/v${{ github.event.inputs.version }} -b v${{ github.event.inputs.version }}
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Build from source
      run: |
        python setup.py sdist
    - name: Publish Doltpy to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: DoltHub
        password: ${{ secrets.pypi_password }}
    - name: Discord Notify
      if: always()
      uses: dolthub/ga-discord-notify@master
      with:
        job-status: ${{ job.status }}
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        notify-on-success: true
