name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Build from source
      run: |
        python setup.py sdist
    - name: Publish Doltpy to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: DoltHub
        password: ${{ secrets.pypi_password }}
